version: "3.7"

services:
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx:1.21.0-alpine
    restart: unless-stopped
    build:
      context: ./cs3219-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - internal

  backend:
    container_name: backend-production
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file: ./backend/.env # .env file for backend
    environment:
      - NODE_ENV=production
    networks:
      - internal

  frontend:
    container_name: frontend-production
    restart: unless-stopped
    ports:
      - "3000:80" # local port to external port
    environment:
      - NODE_PATH=/app/src
    networks:
      - internal
    depends_on:
      - backend

networks:
  internal:

volumes:
  mongo_data: {}
  mongo_config: {}
