version: "3"

services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - cs3219-otot-react
      - main-server
    volumes: # Volumes allow persistant data across life time
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  cs3219-otot-react: # depend_on above depend on this to map properly
    image: cs3219-otot-react
    container_name: cs3219-otot-react
    build:
      context: ./cs3219-otot # path where the dockerfile will be
    depends_on:
      - main-server
    ports:
      - 3000:80 # local port to external port
    restart: on-failure

  main-server:
    image: main-server
    container_name: main-server
    build:
      context: ./backend # path where the dockerfile will be
    ports:
      - 5001:5001
    restart: on-failure
