version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - main-server
    volumes: # Volumes allow persistant data across life time
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  main-server:
    image: main-server
    container_name: main-server
    build:
      context: ./Backend
    ports:
      - 5001:5001 # Mapping local:container
    restart: on-failure
