version: "3.7"

services:
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx:1.21.0-alpine
    restart: unless-stopped
    build:
      context: ./cs3219-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - internal

  backend:
    container_name: backend
    restart: unless-stopped
    build: ./backend # where can you find the Dockerfile to build
    ports:
      - "4000:4000"
    env_file: ./backend/.env # .env file for backend
    environment:
      - NODE_ENV=production
    networks:
      - internal
    depends_on:
      - db

  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./cs3219-frontend # where can you find the Dockerfile to build
    ports:
      - "3000:80" # local port to external port
    environment:
      - NODE_PATH=/app/src
    networks:
      - internal
    depends_on:
      - backend

  db:
    container_name: db
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: node-app
    networks:
      - internal
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

networks:
  internal:

volumes:
  mongo_data: {}
  mongo_config: {}
