apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs3219-otot-react
  labels:
    app: cs3219-otot-react
spec:
    replicas: 2
    selector:
      matchLabels:
        app: cs3219-otot-react
    template:
      metadata:
        labels:
          app: cs3219-otot-react
      spec:
        containers:
          - name: cs3219-otot-react
            image: galvinlwy/cs3219-otot-react
            ports:
              - containerPort: 80
            resources:
                limits:
                    memory: '128Mi'
                    cpu: '200m'
            livenessProbe:
                httpGet:
                    path: /index.html
                    port: 80
                initialDelaySeconds: 15
                timeoutSeconds: 2
                periodSeconds: 5
                failureThreshold: 1
            readinessProbe:
                httpGet:
                    path: /index.html
                    port: 80
                initialDelaySeconds: 15
                periodSeconds: 5
                failureThreshold: 1